# -*- coding: utf-8 -*-
services:
  app:
    build:
      context: .
    image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    restart: always
    entrypoint: gunicorn --bind 0.0.0.0:80 --timeout ${TIMEOUT:-55} main:app
    volumes:
    - ./.env:/app/.env
#    ports:
#      - "9655:80"
    env_file:
      - .env
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      default:
        ipv4_address: $IP_ADDRESS

networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: $NETWORK
